Update authentication.py
Added brackets around 

print (authentication.authorization_url) 

in order for it to print properly with 3.4 otherwise one gets the 

  File "./authentication.py", line 13
    print authentication.authorization_url
                       ^
SyntaxError: Missing parentheses in call to 'print'